services:
  db:
    image: postgres:16
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./api/.env
    ports:
      - 5432:5432

volumes:
  postgres_data: