# Generated by Django 5.1.4 on 2025-01-01 02:53

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('vip', 'VIP'), ('rep', 'REP'), ('std', 'STD')], max_length=3)),
                ('notes', models.CharField(choices=[('faltou', 'FALTOU'), ('esqueceu', 'ESQUECEU'), ('atestado', 'ATESTADO')], max_length=9)),
                ('expected', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), max_length=2, size=None)),
                ('register', django.contrib.postgres.fields.ArrayField(base_field=models.TimeField(), max_length=2, size=None)),
                ('classy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.class')),
            ],
        ),
    ]
